trigger: 
    branches:
      include:
      - master
    paths:
      include:
      - src/arm-templates/infrastructure.json
  
pr: none
  
variables:
  resourceGroup: fagkaffe-infra

stages:
- stage: DeployInfra
  displayName: Deploy Azure Infrastructure
  jobs:
  - job: DeployInfra
    pool: 
      vmImage: 'windows-latest'
    
    steps: 
    - task: AzurePowerShell@4
      displayName: 'Deploy ARM template'
      inputs:
        azureSubscription: 'Visual Studio Professional(8ba210c5-c187-44bb-9d0b-858282bb4487)'
        ScriptType: 'InlineScript'
        Inline: |
          New-AzResourceGroupDeployment -Mode Incremental -Name "fagkaffe-infra" -ResourceGroupName $(resourceGroup) -TemplateFile "$(Build.SourcesDirectory)/arm-templates/infrastructure.json"
          
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'