trigger: none

pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: 'ubuntu-latest'

variables:
  functionsPackage: '$(Pipeline.Workspace)/drop/FagKaffe.Functions.zip'
  apiPackage: '$(Pipeline.Workspace)/drop/FagKaffe.Api.zip'
  prNumber: $(system.pullRequest.pullRequestNumber)

stages:
- stage: DeployARM
  displayName: 'Deploy ARM template'
  dependsOn: []
  variables:
    templateFile: $(Build.SourcesDirectory)/src/arm-templates/pr-specific-resources.json

  jobs:
  - deployment: Deploy
    pool: Private Docker
    displayName: 'Deploy ARM'
    environment: fagkaffe-pr
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzurePowerShell@4
            displayName: 'Deploy ARM infrastructure template'
            inputs:
              azureSubscription: 'Visual Studio Professional(8ba210c5-c187-44bb-9d0b-858282bb4487)'
              ScriptType: 'InlineScript'
              Inline: |
                $prNumber = "$($env:PRNUMBER)"
                $templateFile = $($env:INFRATEMPLATEFILE)
                
                if ($envResourceGroup -eq $null) { throw "Cannot locate resource group for environment '$environment'" }
                $resourceGroup = "fagkaffe-infra"
                
                Write-Host "Using pr number: $prNumber"
                Write-Host "Using resource group: $resourceGroup"
                Write-Host "Using template file: $templateFile"
                
                New-AzResourceGroupDeployment -Mode Incremental `
                  -Name "fagkaffe-infra-$prNumber" `
                  -ResourceGroupName $resourceGroup `
                  -TemplateFile $templateFile `
                  -pr-number $prNumber
                
              FailOnStandardError: true
              azurePowerShellVersion: 'LatestVersion'