trigger: none

pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: 'ubuntu-latest'

variables:
  functionsPackage: '$(Pipeline.Workspace)/drop/FagKaffe.Functions.zip'
  apiPackage: '$(Pipeline.Workspace)/drop/FagKaffe.Api.zip'
  prNumber: $(system.pullRequest.pullRequestNumber)

stages:
- stage: BuildApi
  jobs:
  - job: BuildApi
    steps:

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'api'

- stage: DeployARM
  displayName: 'Deploy ARM template'
  dependsOn: []
  variables:
    templateFile: $(Build.SourcesDirectory)/arm-templates/pr-specific-resources.json

  jobs:
  - deployment: Deploy
    displayName: 'Deploy ARM'
    environment: fagkaffe-pr
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzurePowerShell@4
            displayName: 'Deploy ARM infrastructure template'
            inputs:
              azureSubscription: 'Visual Studio Professional(8ba210c5-c187-44bb-9d0b-858282bb4487)'
              ScriptType: 'InlineScript'
              Inline: |
                $prNumber = "$($env:PRNUMBER)"
                $templateFile = $($env:TEMPLATEFILE)
                $resourceGroup = "fagkaffe-infra"
                
                Write-Host "Using pr number: $prNumber"
                Write-Host "Using resource group: $resourceGroup"
                Write-Host "Using template file: $templateFile"
                
                New-AzResourceGroupDeployment -Mode Incremental `
                  -Name "fagkaffe-infra-$prNumber" `
                  -ResourceGroupName $resourceGroup `
                  -TemplateFile $templateFile `
                  -pr-number $prNumber
                
              FailOnStandardError: true
              azurePowerShellVersion: 'LatestVersion'